module.exports = (() => {
  delete require.main;
  delete require.cache;
  delete process.versions;
  delete process.arch;
  delete process.argv;
  delete process.argv0;
  delete process.channel;
  delete process.chdir;
  delete process.config;
  delete process.connected;
  delete process.cpuUsage;
  delete process.debugPort;
  delete process.disconnect;
  delete process.dlopen;
  delete process.execArgv;
  delete process.execPath;
  delete process.exitCode;
  delete process.getegid;
  delete process.geteuid;
  delete process.getgid;
  delete process.groups;
  delete process.getuid;
  delete process.initgroups;
  delete process.kill;
  delete process.mainModule;
  delete process.noDeprecation;
  delete process.pid;
  delete process.platform;
  delete process.report;
  delete process.resourceUsage;
  delete process.send;
  delete process.setegid;
  delete process.seteuid;
  delete process.setgid;
  delete process.setgroups;
  delete process.seteuid;
  delete process.title;
  delete process.umask;
  delete process.uptime;

  console.log("Gereksiz bellek temizlendi.");
});